import pygame

WINDOW_HEIGHT = 900
WINDOW_WIDTH = 850

PAUSE_TEXT_LOCATION = WINDOW_WIDTH // 2

TEXT_X = WINDOW_HEIGHT // 45
TEXT_Y = WINDOW_HEIGHT // 45
TEXT_SIZE = WINDOW_HEIGHT // 18

BUTTON_X = WINDOW_HEIGHT // 18
BUTTON_Y = WINDOW_HEIGHT // 9
BUTTON_TEXT_SIZE = WINDOW_HEIGHT // 22

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
WALL_COLOUR = BLACK

TIMER = pygame.time.Clock()
FPS = 60

BLOCK_SIZE = WINDOW_WIDTH // 30
COIN_SIZE = WINDOW_HEIGHT // 100

PLAYER_SIZE = WINDOW_HEIGHT // 75
PLAYER_START_X = (6 * BLOCK_SIZE) + (BLOCK_SIZE // 2)
PLAYER_START_Y = (10 * BLOCK_SIZE) + (BLOCK_SIZE // 2)
